# Generated by Django 5.2.16 on 2026-09-19 16:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='General', max_length=100)),
                ('week', models.PositiveSmallIntegerField(default=1, help_text='Week number within the year plan (1–53).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)])),
                ('lesson_date', models.DateField(default=django.utils.timezone.localdate)),
                ('year', models.PositiveSmallIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('date_label', models.CharField(blank=True, help_text='Optional human-readable date label shown to parents.', max_length=60)),
                ('scripture', models.CharField(default='Scripture TBA', max_length=200)),
                ('memory_verse', models.TextField(blank=True, default='Memory verse TBA')),
                ('description', models.TextField(blank=True, default='Sunday school curriculum lesson for parents.')),
                ('status', models.CharField(choices=[('this_week', 'This Week'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], db_index=True, default='upcoming', max_length=20)),
                ('published', models.BooleanField(default=True, help_text='When False the lesson is hidden from parents.')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='curriculum/covers/%Y/%m/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='curriculum/attachments/%Y/%m/')),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('attachment_type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=20)),
                ('objective', models.TextField(blank=True, default='')),
                ('materials', models.JSONField(blank=True, default=list)),
                ('activity', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='classes.classroom')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['-lesson_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published'], name='lessons_les_status_728fae_idx'), models.Index(fields=['year', 'week'], name='lessons_les_year_3d52df_idx')],
                'constraints': [models.UniqueConstraint(fields=('classroom', 'year', 'week'), name='unique_lesson_per_classroom_week')],
            },
        ),
    ]
