# Generated by Django 5.2.16 on 2026-09-21 10:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, default='Grade 1', max_length=50)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('guardian_name', models.CharField(blank=True, default='Parent', help_text="Frontend's `parentName`.", max_length=150)),
                ('guardian_email', models.EmailField(blank=True, default='parent@test.com', help_text="Frontend's `parentEmail`.", max_length=254)),
                ('guardian_contact', models.CharField(blank=True, default='+251', help_text='Existing field — kept for backward compatibility.', max_length=30)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated')], db_index=True, default='active', max_length=50, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster', to='classes.classroom')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['profile__first_name', 'profile__last_name'],
            },
        ),
    ]
