# Generated by Django 5.2.16 on 2026-09-19 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'classroom'], name='students_st_organiz_d221dd_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'status'], name='students_st_organiz_d8da85_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['classroom', 'status'], name='students_st_classro_e1b431_idx'),
        ),
    ]
