# Generated by Django 5.2.16 on 2026-09-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='Event published for parents by admin.')),
                ('event_type', models.CharField(choices=[('service', 'Service'), ('bible_study', 'Bible Study'), ('conference', 'Conference'), ('meeting', 'Meeting'), ('youth', 'Youth'), ('children', 'Children'), ('workshop', 'Workshop'), ('other', 'Other')], default='other', max_length=50)),
                ('location', models.CharField(blank=True, default='Church', max_length=255)),
                ('audience', models.CharField(blank=True, default='Kids & Parents', max_length=150)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('date_label', models.CharField(blank=True, max_length=60)),
                ('time_label', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='upcoming', max_length=20)),
                ('published', models.BooleanField(default=True, help_text='When False the event is hidden from parents.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_datetime'],
            },
        ),
    ]
